// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCukXwbUCi1B5ek-JLMGdLLqhuJuu3vkRU',
    appId: '1:198270633355:web:b6c4ffb1498eab65ecdb8e',
    messagingSenderId: '198270633355',
    projectId: 'falafel-ge401-pro',
    authDomain: 'falafel-ge401-pro.firebaseapp.com',
    storageBucket: 'falafel-ge401-pro.appspot.com',
    measurementId: 'G-KP11ZN4027',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEoD_Tbz4L6KO7vHFADOJJrL-H0-pwR6w',
    appId: '1:198270633355:android:a6184b3b5dae1fb2ecdb8e',
    messagingSenderId: '198270633355',
    projectId: 'falafel-ge401-pro',
    storageBucket: 'falafel-ge401-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAERYtes7C3uCucfaXQ4Ccn3NvI86ePDE',
    appId: '1:198270633355:ios:c66df2185df14595ecdb8e',
    messagingSenderId: '198270633355',
    projectId: 'falafel-ge401-pro',
    storageBucket: 'falafel-ge401-pro.appspot.com',
    iosClientId: '198270633355-fab9o8vv34q1c2qm81s97umlrv3rv55f.apps.googleusercontent.com',
    iosBundleId: 'com.example.falafel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAERYtes7C3uCucfaXQ4Ccn3NvI86ePDE',
    appId: '1:198270633355:ios:c66df2185df14595ecdb8e',
    messagingSenderId: '198270633355',
    projectId: 'falafel-ge401-pro',
    storageBucket: 'falafel-ge401-pro.appspot.com',
    iosClientId: '198270633355-fab9o8vv34q1c2qm81s97umlrv3rv55f.apps.googleusercontent.com',
    iosBundleId: 'com.example.falafel',
  );
}
